#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum FalseInstruction {
    Name(char),
    PushInt(i32),
    PushChar(u8),
    Dup,
    Drop,
    Swap,
    Rot,
    Pick,
    Add,
    Sub,
    Mul,
    Div,
    Neg,
    BitAnd,
    BitOr,
    BitNot,
    Gt,
    Eq,
    Lambda(Vec<FalseInstruction>),
    Execute,
    ConditionalExecute(Vec<FalseInstruction>),
    WhileLoop(Vec<FalseInstruction>, Vec<FalseInstruction>),
    Store,
    Fetch,
    ReadChar,
    WriteChar,
    WriteStr(String),
    WriteInt,
    Flush,
}
